<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \App\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'idprod', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'nomprod', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'prixprod', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'localisationprod', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'typeprod', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'typestatue', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'imagem1', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'rating'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'idprod', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'nomprod', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'prixprod', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'localisationprod', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'typeprod', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'typestatue', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'imagem1', '' . "\0" . 'App\\Entity\\Produit' . "\0" . 'rating'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdprod(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdprod();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdprod', []);

        return parent::getIdprod();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomprod(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomprod', []);

        return parent::getNomprod();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomprod(string $nomprod): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomprod', [$nomprod]);

        return parent::setNomprod($nomprod);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixprod(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixprod', []);

        return parent::getPrixprod();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixprod(float $prixprod): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixprod', [$prixprod]);

        return parent::setPrixprod($prixprod);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalisationprod(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalisationprod', []);

        return parent::getLocalisationprod();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalisationprod(string $localisationprod): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalisationprod', [$localisationprod]);

        return parent::setLocalisationprod($localisationprod);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeprod(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeprod', []);

        return parent::getTypeprod();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeprod(string $typeprod): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeprod', [$typeprod]);

        return parent::setTypeprod($typeprod);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypestatue(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypestatue', []);

        return parent::getTypestatue();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypestatue(string $typestatue): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypestatue', [$typestatue]);

        return parent::setTypestatue($typestatue);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagem1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagem1', []);

        return parent::getImagem1();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagem1(string $imagem1): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagem1', [$imagem1]);

        return parent::setImagem1($imagem1);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', []);

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function addRating(\App\Entity\Like $rating): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRating', [$rating]);

        return parent::addRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRating(\App\Entity\Like $rating): \App\Entity\Produit
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRating', [$rating]);

        return parent::removeRating($rating);
    }

}
