<?php

namespace ContainerSzOK3ig;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EBa9r43Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eBa9r43' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eBa9r43'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandpm' => ['privates', '.errored..service_locator.eBa9r43.App\\Entity\\Commandpm', NULL, 'Cannot autowire service ".service_locator.eBa9r43": it references class "App\\Entity\\Commandpm" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commandpm' => 'App\\Entity\\Commandpm',
            'entityManager' => '?',
        ]);
    }
}
