<?php

namespace ContainerSzOK3ig;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoriquevente2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Fq9PTeA.App\Entity\Historiquevente' shared service.
     *
     * @return \App\Entity\Historiquevente
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Fq9PTeA": it references class "App\\Entity\\Historiquevente" but no such service exists.');
    }
}
