<?php

namespace ContainerC731nta;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RwIJHlAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rwIJHlA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rwIJHlA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produitpm' => ['privates', '.errored..service_locator.rwIJHlA.App\\Entity\\Produitpm', NULL, 'Cannot autowire service ".service_locator.rwIJHlA": it references class "App\\Entity\\Produitpm" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'produitpm' => 'App\\Entity\\Produitpm',
        ]);
    }
}
