<?php

namespace ContainerC731nta;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BfsaHVAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BfsaHVA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BfsaHVA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'historiquevente' => ['privates', '.errored..service_locator.BfsaHVA.App\\Entity\\Historiquevente', NULL, 'Cannot autowire service ".service_locator.BfsaHVA": it references class "App\\Entity\\Historiquevente" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'historiquevente' => 'App\\Entity\\Historiquevente',
        ]);
    }
}
