<?php

namespace ContainerC731nta;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandpm2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eBa9r43.App\Entity\Commandpm' shared service.
     *
     * @return \App\Entity\Commandpm
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.eBa9r43": it references class "App\\Entity\\Commandpm" but no such service exists.');
    }
}
