<?php

namespace ContainerC731nta;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitpmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rwIJHlA.App\Entity\Produitpm' shared service.
     *
     * @return \App\Entity\Produitpm
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.rwIJHlA": it references class "App\\Entity\\Produitpm" but no such service exists.');
    }
}
