<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSzOK3ig\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSzOK3ig/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSzOK3ig.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSzOK3ig\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSzOK3ig\App_KernelDevDebugContainer([
    'container.build_hash' => 'SzOK3ig',
    'container.build_id' => '2a0f669e',
    'container.build_time' => 1670101096,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSzOK3ig');
